import { basename } from 'jsr:@std/path'
import hljs from 'https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.11.0/build/es/highlight.min.js'

const languagesUrl = 'https://cdn.jsdelivr.net/npm/@highlightjs/cdn-assets@11.11.0/es/languages/'

const names = (await (await fetch(languagesUrl)).text()).matchAll(/>(.+)\.min\.js</g).map(match => match[1])

console.log(`// Generated by ${basename(import.meta.filename ?? 'unknown')}`)

console.log(`export const hljsLanguagesUrl = '${languagesUrl}'`)

console.log('export const hljsExtraAliases = [')

for (const name of names) {
  if (hljs.getLanguage(name) != null) {
    continue
  }

  const { default: module } = await import(
    `${languagesUrl}${name}.min.js`
  )

  hljs.registerLanguage(name, module)

  const aliases = [name, ...(hljs.getLanguage(name).aliases ?? [])]

  console.log(`  [${aliases.map(name => `'${name}'`).join(', ')}],`)
}

console.log(']')
